Homework1
made-ml-in-prod-2021/sonomama pull request #2
Opened 2021-04-26 18:11 UTC by sonomama

Структуру взяла из примера с лекции. Параметры для обучения берутся из train_config.yaml. Так как обучатся могут логрегрессия и случайный лес, то для них есть возможность указать или опустить scaler, который используется в трансформере. В тестах есть второй конфиг с логрегрессией и скейлером, тогда как основной конфиг написан для леса и без скейлера. 

Есть отдельный конфиг для логов, которые пишутся в файл и в sys::stderr, в файл пишется все уровня INFO, в стандартный - DEBUG. В tests находятся тесты на почти все модули, а в папке tests/models еще и test_end2end.py для всего пайплайна. Для тестов я сгенерировала фейковые данные с пропусками с помощью faker. Для этого в test_make_dataset сделана fixture fake_data, которая потом используется, кроме того она же сохранена как csv. 

В ноутбуке построила pair_plots для фич, особо полезного не вынесла из этого, так что особо данные решила не преобразовывать и только со скейлерами поиграться . Качество смотрела по roc_auc, f1 и recall.

Самооценка: 
-2) Назовите ветку homework1  + 1
0) Описание работы в пул реквесте + 2
1) Выполнение EDA, закоммитьте ноутбук в папку с ноутбуками + 2
как делать репорт и скрипт к нему не поняла, если посоветуете -- доделаю :)
2) Проект имеет модульную структуру + 2
3) использованы логгеры + 2
4) написаны тесты на отдельные модули и на прогон всего пайплайна +3
5) Для тестов генерируются синтетические данные, приближенные к реальным +3 
6) Обучение модели конфигурируется с помощью конфигов в json или yaml, закоммитьте как минимум 2 корректные конфигурации, с помощью которых можно обучить модель (разные модели, стратегии split, preprocessing) + 3
7) Используются датаклассы для сущностей из конфига, а не голые dict +3
8) Используйте кастомный трансформер(написанный своими руками) и протестируйте его +3
9) Обучите модель, запишите в readme как это предлагается +3
10) напишите функцию predict, которая примет на вход артефакт/ы от обучения, тестовую выборку(без меток) и запишет предикт, напишите в readme как это сделать +3
13) Проведите самооценку, опишите, в какое колво баллов по вашему мнению стоит оценить вашу работу и почему + 1

Вроде выходит возможный максимум 31 (но я ожидала что без репорта должно быть 30?)

2021-04-28 10:12 UTC, asv715 commented on ml_project/data/make_dataset.py
> +    data = pd.read_csv(path)
Здесь и далее по коду перед `return` можно делать отбивку в виде пустой строки - это повышает читаемость

2021-04-28 10:12 UTC, asv715 commented on ml_project/features/build_features.py
> +    scaler_str = preprocessing_params.scaler
Перед и после `if` тоже можно строки пропускать

2021-04-28 10:12 UTC, asv715 commented on ml_project/features/build_features.py
> +    if scaler_str != "None":
Именно со строкой сравнение? Возможно было бы удобнее использовать Boolean или натуральный None?

2021-04-28 10:12 UTC, asv715 commented on ml_project/models/utils.py
> +        raise NotImplementedError()
Тут не совсем верно кидать `NotImplementedError`, так как метод реализован, но не смог отработать из-за неверных параметров. Следует записать инфу об ошибке в логи (возможно даже уровня Critical, так как это фактически главный метод) и кинуть, например, `ValueError`

2021-04-28 10:12 UTC, asv715 commented on ml_project/models/utils.py
> +    return output
Зачем этот метод возвращает имя файла?

2021-04-28 10:12 UTC, asv715 commented on ml_project/params/split_params.py
> +    random_state: int = 1984
Эти значения можно брать из конфига?

2021-04-28 10:14 UTC, asv715 commented on ml_project/tests/data/test_make_dataset.py
> +        "fake data does not have NaNs"
В фикстурах корректно ассерты проверять?

2021-04-28 10:16 UTC, asv715 commented on ml_project/tests/data/test_make_dataset.py
> +def test_load_dataset(fake_data):
Названия тестов часто пишут с глаголами типа `can`. В данном случае `test_can_load_dataset`

2021-04-28 10:17 UTC, asv715 commented on ml_project/tests/features/test_process_features.py
> +        assert features.shape[1] > fake_data.shape[1]
Думаю, в этой группе ассертов было бы полезным вывод сообщений

2021-04-28 10:18 UTC, asv715 commented on ml_project/tests/models/test_end2end.py
> +    assert os.path.exists(params.metric_path)
Здесь тоже

2021-04-28 10:21 UTC, asv715 approved these changes
Работа заслуживает 31 балл (как автор и указал). Все пункты соблюдены, код чистый, все четко

2021-04-28 16:24 UTC, sonomama commented on ml_project/tests/data/test_make_dataset.py
> +        "fake data does not have NaNs"
хороший вопрос. наверное, лучше вынести в тест

2021-04-28 17:30 UTC, sonomama commented on ml_project/params/split_params.py
> +    random_state: int = 1984
Да, там есть 
splitting_params:
  test_size: 0.2
  random_state: 1984
тут я просто по дефолту указала значения

2021-05-03 16:13 UTC, ol-ga-00 commented
Под пунктом «положите код в папку ml_project» (пункт -1) подразумевалось в корне проекта создать папку ml_project (аналог папки ml_project_example репозитория Михаила https://github.com/made-ml-in-prod-2021/ml_project_example), в которую необходимо разместить код всей первой домашки в том числе и README.md, и setup.py (в корне проекта также лучше оставить ещё один README с какой-то супер общей информацией о репозитории sonomama).  При выполнении pip install ml_project/ формируется пакет, который в себе содержит только .py файлы. По этой причине в репозитории следует явно разделять скрипты, которые будут использовать пользователи при установке себе этого пакета, и файлы, вместо которых пользователи будут подкладывать что-то своё. 
На примере репозитория Михаила:  скрипты, которые попадут в пакет, находятся в ml_project_example/ml_example  и ml_project_example/tests (там только .py файлы), а csv/jsom/yaml/… файлы находятся в других папках (и в них нет .py файлов). ___Данная структура очень удобная, рекомендую повторить её для данного проекта .___
 К примеру, в этом pr в папке data присутствует как py файл, который будут использовать пользователи, так и raw с csv файлом, который является частным случаем, и пользователи вместо него захотят положить что-то своё.

2021-05-03 16:28 UTC, ol-ga-00 commented
В отношении тестов рекомендую изучить статью https://habr.com/ru/post/448786/
Обратить внимание следует на "Обмен Fixtures через conftest.py" и "Спецификация областей(Scope) Fixture
"

При запуске тестов через команду python -m pytest --setup-show ml_project/tests/ можно увидеть, что каждая фикстура сейчас вычисляется +- 5 раз:
```
ml_project/tests/data/test_make_dataset.py 
SETUP    S _session_faker
        SETUP    F data
        SETUP    F fake_data (fixtures used: data)
        ml_project/tests/data/test_make_dataset.py::test_can_load_dataset (fixtures used: _session_faker, data, fake_data, request).
        TEARDOWN F fake_data
        TEARDOWN F data
        SETUP    F data
        SETUP    F fake_data (fixtures used: data)
        ml_project/tests/data/test_make_dataset.py::test_can_split_dataset (fixtures used: _session_faker, data, fake_data, request).
        TEARDOWN F fake_data
        TEARDOWN F data
ml_project/tests/features/test_process_features.py 
        SETUP    F data
        SETUP    F fake_data (fixtures used: data)
        SETUP    F feature_params
        ml_project/tests/features/test_process_features.py::test_can_transform_features (fixtures used: _session_faker, data, fake_data, feature_params, request).
        TEARDOWN F feature_params
        TEARDOWN F fake_data
        TEARDOWN F data
        SETUP    F data
        SETUP    F fake_data (fixtures used: data)
        SETUP    F feature_params
        ml_project/tests/features/test_process_features.py::test_can_get_target (fixtures used: _session_faker, data, fake_data, feature_params, request).
        TEARDOWN F feature_params
        TEARDOWN F fake_data
        TEARDOWN F data
ml_project/tests/models/test_end2end.py 
        ml_project/tests/models/test_end2end.py::test_can_train_e2e (fixtures used: _session_faker, request).
ml_project/tests/models/test_train_model.py 
        SETUP    F data
        SETUP    F fake_data (fixtures used: data)
        SETUP    F feature_params
        SETUP    F preprocessing_params
        SETUP    F features_and_target (fixtures used: fake_data, feature_params, preprocessing_params)
        ml_project/tests/models/test_train_model.py::test_can_train_model (fixtures used: _session_faker, data, fake_data, feature_params, features_and_target, preprocessing_params, request).
        TEARDOWN F features_and_target
        TEARDOWN F preprocessing_params
        TEARDOWN F feature_params
        TEARDOWN F fake_data
        TEARDOWN F data
SETUP    S tmp_path_factory
        SETUP    F tmp_path (fixtures used: tmp_path_factory)
        SETUP    F tmpdir (fixtures used: tmp_path)
        ml_project/tests/models/test_train_model.py::test_can_save_model (fixtures used: _session_faker, request, tmp_path, tmp_path_factory, tmpdir).
        TEARDOWN F tmpdir
        TEARDOWN F tmp_path
TEARDOWN S tmp_path_factory
TEARDOWN S _session_faker
```
___Прошу добавить использование conftest.py и scope___

2021-05-04 11:14 UTC, ol-ga-00 requested changes
Написала два комментария, после их исправления поставлю баллы

2021-05-05 13:44 UTC, ol-ga-00 commented
Кстати, прошу уточнить, где реализован кастомный трансформер

Требовалось придумать и реализовать его самому
Пример,
https://towardsdatascience.com/pipelines-custom-transformers-in-scikit-learn-the-step-by-step-guide-with-python-code-4a7d9b068156

2021-05-05 14:28 UTC, sonomama commented
@ol-ga-00 трансформер написан в features/build_features.py. Тоже увидела эту ссылку на пример в дискорде сегодня, но до этого я видимо не поняла задание, потому что Михаил упоминал, что можно использовать column transformer. Могли бы вы подсказать как мне переделать метод build_transformer? Можно ли пользоваться пайплайном? Можно ли пользоваться стандартными скейлерами и тп или нужно их с нуля написать?

2021-05-05 14:30 UTC, sonomama commented
@ol-ga-00 Так же переделала структуру, посмотрите, пожалуйста, правильно ли

2021-05-05 14:50 UTC, ol-ga-00 commented
> @ol-ga-00 Так же переделала структуру, посмотрите, пожалуйста, правильно ли

ml_project/ml_pipeline выглядит корректным
только теперь из ml_project/data, ml_project/features, ml_project/models, ml_project/params следует удалить .py файлы
они же нигде теперь больше не используются (и дублируют то, что находится в ml_pipeline)

2021-05-05 14:58 UTC, ol-ga-00 commented
> @ol-ga-00 трансформер написан в features/build_features.py. Тоже увидела эту ссылку на пример в дискорде сегодня, но до этого я видимо не поняла задание, потому что Михаил упоминал, что можно использовать column transformer. Могли бы вы подсказать как мне переделать метод build_transformer? Можно ли пользоваться пайплайном? Можно ли пользоваться стандартными скейлерами и тп или нужно их с нуля написать?

Можете использовать пайплайн и можете использовать стандартные трансформеры, но чтобы получить баллы, необходимо дополнительно написать ещё один свой

2021-05-06 09:59 UTC, sonomama commented
@ol-ga-00 добавила трансформер и поправила тесты: все фикстуры лежат в conftest.py со scope="session". Теперь при запуске вот так выглядит. Старые папки из ml_project удалила.

                                                                                                                                                              tests/data/test_make_dataset.py 
SETUP    S _session_faker
SETUP    S data
SETUP    S fake_data (fixtures used: data)
        tests/data/test_make_dataset.py::test_can_load_dataset (fixtures used: _session_faker, data, fake_data, request).
        tests/data/test_make_dataset.py::test_can_split_dataset (fixtures used: _session_faker, data, fake_data, request).
tests/features/test_process_features.py 
        tests/features/test_process_features.py::test_can_scale_features (fixtures used: _session_faker, data, fake_data, request).
SETUP    S feature_params
SETUP    S preprocessing_params
        tests/features/test_process_features.py::test_can_transform_features (fixtures used: _session_faker, data, fake_data, feature_params, preprocessing_params, request).
        tests/features/test_process_features.py::test_can_get_target (fixtures used: _session_faker, data, fake_data, feature_params, request).
tests/models/test_end2end.py 
        tests/models/test_end2end.py::test_can_train_e2e (fixtures used: _session_faker, request).
tests/models/test_train_model.py 
SETUP    S features_and_target (fixtures used: fake_data, feature_params, preprocessing_params)
        tests/models/test_train_model.py::test_can_train_model (fixtures used: _session_faker, data, fake_data, feature_params, features_and_target, preprocessing_params, request).
SETUP    S tmp_path_factory
        SETUP    F tmp_path (fixtures used: tmp_path_factory)
        SETUP    F tmpdir (fixtures used: tmp_path)
        tests/models/test_train_model.py::test_can_save_model (fixtures used: _session_faker, request, tmp_path, tmp_path_factory, tmpdir).
        TEARDOWN F tmpdir
        TEARDOWN F tmp_path
TEARDOWN S tmp_path_factory
TEARDOWN S _session_faker
TEARDOWN S features_and_target
TEARDOWN S preprocessing_params
TEARDOWN S feature_params
TEARDOWN S fake_data
TEARDOWN S data

2021-05-06 10:22 UTC, ol-ga-00 approved these changes
С самооценкой согласна
Ставлю 31 балл

2021-05-08 10:49 UTC, ol-ga-00 commented
@sonomama, если у вас больше нет вопросов по этому pr, то вы можете его смёржить, так как два апрува вы получили :)

2021-05-08 22:08 UTC, merged